### ISSUE TITLE
After page break, in next page the first line is empty.

### ISSUE THREAD

**Issue by lamalien** [karmapa/ketaka-lite#53] opened 2015-10-20 01:06 UTC
![ketaka_lite_issue_7_19102015](https://cloud.githubusercontent.com/assets/5266492/10595360/bf2e4de4-7709-11e5-9d36-a49153cc4ad9.png)

**Comment by kmsheng** [comment] 2015-10-21 18:43
@lamalien can't reproduce this

**Comment by chiehan1** [comment] 2015-10-26 04:52
If pagebreaking at line end, the \n or \r\n seems to be pagebreaked to the next page at the same time, so the next page will show an empty first line.
What 法海師 concerned is that if fixed, will the \n or \n\r disappear in the exported whole txt?

**Comment by kmsheng** [comment] 2015-10-26 13:43
It doesn't show an empty first line for current version.

**Comment by chiehan1** [comment] 2015-10-27 03:01
I tried v0.1.17 in windows version, it shows an empty line in next page after pagebreak.
Allen says relatively this is a small problem, users should pagebreak at the beginning of a line or at the middle of a line. 
We haven't discussed this issue with Lamalien yet and he goes abroad for 5 days. So maybe we can discuss this issue later.
figure1
![pbreak1](https://cloud.githubusercontent.com/assets/13195099/10748237/2128585c-7c99-11e5-878a-f9af3120bd46.jpg)
figure2
![pbreak2](https://cloud.githubusercontent.com/assets/13195099/10748238/23947602-7c99-11e5-8d2b-d3f1ded1d716.jpg)

**Comment by kmsheng** [comment] 2015-10-27 05:33
This will be fixed in the next release.

**Comment by kmsheng** [comment] 2015-10-27 07:02
fixed in v0.1.18

**Closed as completed by kmsheng** 2015-10-27 07:02 UTC
Labels: help wanted
