### ISSUE TITLE
in mac, replace-one-by-one doesn't work if cursor is not at the text area and not before the searched tokens 

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#60] opened 2015-10-22 07:49 UTC
for example, if the cursor is in the text area(orange square at the bottom) but not before the searched words, replace-one-by-one will fail.
![replace](https://cloud.githubusercontent.com/assets/13195099/10659484/d9cded92-78d2-11e5-9cc6-90d3241d3235.JPG)

and after keying in the searched word at the replace window, if not click the text area by mouse first, replace-one-by-one doesn't work either.

**Comment by kmsheng** [comment] 2015-10-22 08:44
This is by design.

**Comment by kmsheng** [comment] 2015-10-24 07:23
it's fixed on the latest version

**Closed as completed by kmsheng** 2015-10-24 07:23 UTC
Labels: help wanted
