### ISSUE TITLE
cancel spell check when pressing the spell-check button again

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#45] opened 2015-10-05 06:46 UTC
The first time press the spell-check button, spell check function will be open, and the wrong words will be underlined. And the second time press the same button, the underline will disappear.

**Comment by kmsheng** [comment] 2015-10-05 08:54
duplicate of https://github.com/karmapa/ketaka-lite/issues/36

**Closed as completed** 2015-10-22 10:59 UTC
Labels: duplicate, enhancement
